name: Build APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y docutils git libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake gettext
        pip install --upgrade pip
        # Latest python-for-android tools force karne ke liye git version install kiya
        pip install git+https://github.com
        pip install git+https://github.com
        pip install cython

    - name: Build APK with Buildozer
      run: |
        rm -rf .buildozer
        rm -rf bin
        yes | buildozer -v android debug
